########################################################################
########################################################################
## This is a sample configuration file for the ftpsync mirror script. ##
## Only options most users may need are included.  For documentation  ##
## and all available options see ftpsync.conf(5).                     ##
########################################################################
########################################################################

MIRRORNAME="mirrors.zju.edu.cn"
TO="/srv/mirrors/storage/"
MAILTO="root@localhost"
HUB=false

########################################################################
## Connection options
########################################################################

RSYNC_HOST="mirrors.ustc.edu.cn"
RSYNC_PATH="debian"
# RSYNC_TRANSPORT="ssh"
# RSYNC_SSL_METHOD="socat"
RSYNC_EXTRA="-4"
# RSYNC_USER=
# RSYNC_PASSWORD=

########################################################################
## Mirror information options
########################################################################

# INFO_MAINTAINER="ZJUSCT Falcon Team <mirrors@zju.edu.cn>"
INFO_COUNTRY=CN
# INFO_LOCATION="Zhejiang University"
# INFO_SPONSOR="Example <https://example.com>"
# INFO_THROUGHPUT=10Gb

########################################################################
## Include and exclude options
########################################################################

ARCH_INCLUDE="source amd64 i386 arm64 armel armhf riscv64"
# ARCH_EXCLUDE=

########################################################################
## Log option
########################################################################

LOGDIR="/mirrorlogs/"
