services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mirrorgo:latest
    container_name: mirrorgo
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ZERLOG_LEVEL=info
    volumes:
      - ./Configs:/Configs:ro
      - /home/zjusct/mirrorgo/logs:/home/zjusct/mirrorgo/logs
      - /home/zjusct/mirrorgo/mirrorgo.json:/home/zjusct/mirrorgo/mirrorgo.json
      - ./state.db:/state.db
      - ./state.db-shm:/state.db-shm
      - ./state.db-wal:/state.db-wal
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker # for container logs
    restart: unless-stopped

volumes: {}


