//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mirror) DeepCopyInto(out *Mirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mirror.
func (in *Mirror) DeepCopy() *Mirror {
	if in == nil {
		return nil
	}
	out := new(Mirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorCurrentSyncStatus) DeepCopyInto(out *MirrorCurrentSyncStatus) {
	*out = *in
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorCurrentSyncStatus.
func (in *MirrorCurrentSyncStatus) DeepCopy() *MirrorCurrentSyncStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorCurrentSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorHTTPServiceSpec) DeepCopyInto(out *MirrorHTTPServiceSpec) {
	*out = *in
	in.MirrorServiceSpec.DeepCopyInto(&out.MirrorServiceSpec)
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]MirrorHTTPAlias, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorHTTPServiceSpec.
func (in *MirrorHTTPServiceSpec) DeepCopy() *MirrorHTTPServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorHTTPServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorInfo) DeepCopyInto(out *MirrorInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorInfo.
func (in *MirrorInfo) DeepCopy() *MirrorInfo {
	if in == nil {
		return nil
	}
	out := new(MirrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorList) DeepCopyInto(out *MirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorList.
func (in *MirrorList) DeepCopy() *MirrorList {
	if in == nil {
		return nil
	}
	out := new(MirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPublicationStatus) DeepCopyInto(out *MirrorPublicationStatus) {
	*out = *in
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPublicationStatus.
func (in *MirrorPublicationStatus) DeepCopy() *MirrorPublicationStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorPublicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorRequestCleanup) DeepCopyInto(out *MirrorRequestCleanup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorRequestCleanup.
func (in *MirrorRequestCleanup) DeepCopy() *MirrorRequestCleanup {
	if in == nil {
		return nil
	}
	out := new(MirrorRequestCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorServiceSpec) DeepCopyInto(out *MirrorServiceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorServiceSpec.
func (in *MirrorServiceSpec) DeepCopy() *MirrorServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorServicesSpec) DeepCopyInto(out *MirrorServicesSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(MirrorHTTPServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rsync != nil {
		in, out := &in.Rsync, &out.Rsync
		*out = new(MirrorServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorServicesSpec.
func (in *MirrorServicesSpec) DeepCopy() *MirrorServicesSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSnapshotStatus) DeepCopyInto(out *MirrorSnapshotStatus) {
	*out = *in
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSnapshotStatus.
func (in *MirrorSnapshotStatus) DeepCopy() *MirrorSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSpec) DeepCopyInto(out *MirrorSpec) {
	*out = *in
	out.Info = in.Info
	in.Sync.DeepCopyInto(&out.Sync)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Publish.DeepCopyInto(&out.Publish)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSpec.
func (in *MirrorSpec) DeepCopy() *MirrorSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorStatus) DeepCopyInto(out *MirrorStatus) {
	*out = *in
	if in.RequestCleanup != nil {
		in, out := &in.RequestCleanup, &out.RequestCleanup
		*out = new(MirrorRequestCleanup)
		**out = **in
	}
	if in.LastAcceptedSyncAt != nil {
		in, out := &in.LastAcceptedSyncAt, &out.LastAcceptedSyncAt
		*out = (*in).DeepCopy()
	}
	if in.LastSnapshot != nil {
		in, out := &in.LastSnapshot, &out.LastSnapshot
		*out = new(MirrorSnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Sync = in.Sync
	if in.Publication != nil {
		in, out := &in.Publication, &out.Publication
		*out = new(MirrorPublicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentSync != nil {
		in, out := &in.CurrentSync, &out.CurrentSync
		*out = new(MirrorCurrentSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextSyncAt != nil {
		in, out := &in.NextSyncAt, &out.NextSyncAt
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulSyncAt != nil {
		in, out := &in.LastSuccessfulSyncAt, &out.LastSuccessfulSyncAt
		*out = (*in).DeepCopy()
	}
	if in.PausedAt != nil {
		in, out := &in.PausedAt, &out.PausedAt
		*out = (*in).DeepCopy()
	}
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = new(MirrorSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastPublishedAt != nil {
		in, out := &in.LastPublishedAt, &out.LastPublishedAt
		*out = (*in).DeepCopy()
	}
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = new(MirrorSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorStatus.
func (in *MirrorStatus) DeepCopy() *MirrorStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorStorageSpec) DeepCopyInto(out *MirrorStorageSpec) {
	*out = *in
	in.PVCSpec.DeepCopyInto(&out.PVCSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorStorageSpec.
func (in *MirrorStorageSpec) DeepCopy() *MirrorStorageSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSyncSpec) DeepCopyInto(out *MirrorSyncSpec) {
	*out = *in
	out.Interval = in.Interval
	out.RetryInterval = in.RetryInterval
	out.Timeout = in.Timeout
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSyncSpec.
func (in *MirrorSyncSpec) DeepCopy() *MirrorSyncSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSyncState) DeepCopyInto(out *MirrorSyncState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSyncState.
func (in *MirrorSyncState) DeepCopy() *MirrorSyncState {
	if in == nil {
		return nil
	}
	out := new(MirrorSyncState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSyncStatus) DeepCopyInto(out *MirrorSyncStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSyncStatus.
func (in *MirrorSyncStatus) DeepCopy() *MirrorSyncStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirror) DeepCopyInto(out *ProxyMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirror.
func (in *ProxyMirror) DeepCopy() *ProxyMirror {
	if in == nil {
		return nil
	}
	out := new(ProxyMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorCacheSpec) DeepCopyInto(out *ProxyMirrorCacheSpec) {
	*out = *in
	in.PVCSpec.DeepCopyInto(&out.PVCSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorCacheSpec.
func (in *ProxyMirrorCacheSpec) DeepCopy() *ProxyMirrorCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorList) DeepCopyInto(out *ProxyMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorList.
func (in *ProxyMirrorList) DeepCopy() *ProxyMirrorList {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorServicesSpec) DeepCopyInto(out *ProxyMirrorServicesSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(ProxyMirrorServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorServicesSpec.
func (in *ProxyMirrorServicesSpec) DeepCopy() *ProxyMirrorServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorSpec) DeepCopyInto(out *ProxyMirrorSpec) {
	*out = *in
	in.Info.DeepCopyInto(&out.Info)
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(ProxyMirrorCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Publish.DeepCopyInto(&out.Publish)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorSpec.
func (in *ProxyMirrorSpec) DeepCopy() *ProxyMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorStatus) DeepCopyInto(out *ProxyMirrorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorStatus.
func (in *ProxyMirrorStatus) DeepCopy() *ProxyMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorStatus)
	in.DeepCopyInto(out)
	return out
}
