//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LocalizedString) DeepCopyInto(out *LocalizedString) {
	{
		in := &in
		*out = make(LocalizedString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalizedString.
func (in LocalizedString) DeepCopy() LocalizedString {
	if in == nil {
		return nil
	}
	out := new(LocalizedString)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mirror) DeepCopyInto(out *Mirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mirror.
func (in *Mirror) DeepCopy() *Mirror {
	if in == nil {
		return nil
	}
	out := new(Mirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorCurrentSyncStatus) DeepCopyInto(out *MirrorCurrentSyncStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorCurrentSyncStatus.
func (in *MirrorCurrentSyncStatus) DeepCopy() *MirrorCurrentSyncStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorCurrentSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorHTTPServiceSpec) DeepCopyInto(out *MirrorHTTPServiceSpec) {
	*out = *in
	in.MirrorServiceSpec.DeepCopyInto(&out.MirrorServiceSpec)
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]MirrorHTTPAlias, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorHTTPServiceSpec.
func (in *MirrorHTTPServiceSpec) DeepCopy() *MirrorHTTPServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorHTTPServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorInfo) DeepCopyInto(out *MirrorInfo) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = make(LocalizedString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = make(LocalizedString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorInfo.
func (in *MirrorInfo) DeepCopy() *MirrorInfo {
	if in == nil {
		return nil
	}
	out := new(MirrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorList) DeepCopyInto(out *MirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorList.
func (in *MirrorList) DeepCopy() *MirrorList {
	if in == nil {
		return nil
	}
	out := new(MirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorRetentionSpec) DeepCopyInto(out *MirrorRetentionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorRetentionSpec.
func (in *MirrorRetentionSpec) DeepCopy() *MirrorRetentionSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorRetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorServiceSpec) DeepCopyInto(out *MirrorServiceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorServiceSpec.
func (in *MirrorServiceSpec) DeepCopy() *MirrorServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorServicesSpec) DeepCopyInto(out *MirrorServicesSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(MirrorHTTPServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rsync != nil {
		in, out := &in.Rsync, &out.Rsync
		*out = new(MirrorServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorServicesSpec.
func (in *MirrorServicesSpec) DeepCopy() *MirrorServicesSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSpec) DeepCopyInto(out *MirrorSpec) {
	*out = *in
	in.Info.DeepCopyInto(&out.Info)
	in.Sync.DeepCopyInto(&out.Sync)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Services.DeepCopyInto(&out.Services)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSpec.
func (in *MirrorSpec) DeepCopy() *MirrorSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorStatus) DeepCopyInto(out *MirrorStatus) {
	*out = *in
	if in.CurrentSync != nil {
		in, out := &in.CurrentSync, &out.CurrentSync
		*out = new(MirrorCurrentSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextSyncAt != nil {
		in, out := &in.NextSyncAt, &out.NextSyncAt
		*out = (*in).DeepCopy()
	}
	if in.LastPublishedAt != nil {
		in, out := &in.LastPublishedAt, &out.LastPublishedAt
		*out = (*in).DeepCopy()
	}
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = new(MirrorSyncStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorStatus.
func (in *MirrorStatus) DeepCopy() *MirrorStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorStorageSpec) DeepCopyInto(out *MirrorStorageSpec) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorStorageSpec.
func (in *MirrorStorageSpec) DeepCopy() *MirrorStorageSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSyncSpec) DeepCopyInto(out *MirrorSyncSpec) {
	*out = *in
	out.Interval = in.Interval
	out.RetryInterval = in.RetryInterval
	out.Timeout = in.Timeout
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSyncSpec.
func (in *MirrorSyncSpec) DeepCopy() *MirrorSyncSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSyncStatus) DeepCopyInto(out *MirrorSyncStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSyncStatus.
func (in *MirrorSyncStatus) DeepCopy() *MirrorSyncStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirror) DeepCopyInto(out *ProxyMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirror.
func (in *ProxyMirror) DeepCopy() *ProxyMirror {
	if in == nil {
		return nil
	}
	out := new(ProxyMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorCacheSpec) DeepCopyInto(out *ProxyMirrorCacheSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorCacheSpec.
func (in *ProxyMirrorCacheSpec) DeepCopy() *ProxyMirrorCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorInfo) DeepCopyInto(out *ProxyMirrorInfo) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = make(LocalizedString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = make(LocalizedString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorInfo.
func (in *ProxyMirrorInfo) DeepCopy() *ProxyMirrorInfo {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorList) DeepCopyInto(out *ProxyMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorList.
func (in *ProxyMirrorList) DeepCopy() *ProxyMirrorList {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorProxySpec) DeepCopyInto(out *ProxyMirrorProxySpec) {
	*out = *in
	in.Cache.DeepCopyInto(&out.Cache)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorProxySpec.
func (in *ProxyMirrorProxySpec) DeepCopy() *ProxyMirrorProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorServiceSpec) DeepCopyInto(out *ProxyMirrorServiceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorServiceSpec.
func (in *ProxyMirrorServiceSpec) DeepCopy() *ProxyMirrorServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorServicesSpec) DeepCopyInto(out *ProxyMirrorServicesSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(ProxyMirrorServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorServicesSpec.
func (in *ProxyMirrorServicesSpec) DeepCopy() *ProxyMirrorServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorSpec) DeepCopyInto(out *ProxyMirrorSpec) {
	*out = *in
	in.Info.DeepCopyInto(&out.Info)
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.Services.DeepCopyInto(&out.Services)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorSpec.
func (in *ProxyMirrorSpec) DeepCopy() *ProxyMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMirrorStatus) DeepCopyInto(out *ProxyMirrorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMirrorStatus.
func (in *ProxyMirrorStatus) DeepCopy() *ProxyMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyMirrorStatus)
	in.DeepCopyInto(out)
	return out
}
