[mirror]
directory = /srv/pypi
json = true
release-files = true
cleanup = false

master = https://pypi.org
; master = https://pypi.tuna.tsinghua.edu.cn
; master = https://mirrors6.tuna.tsinghua.edu.cn/pypi/web
timeout = 30
global-timeout = 1800
workers = 5
hash-index = false
simple-format = ALL
stop-on-error = false
storage-backend = filesystem

; Advanced logging configuration. Uncomment and set to the location of a
; python logging format logging config file.
; log-config = /etc/bandersnatch-log.conf

verifiers = 3
compare-method = stat
; download-mirror = https://mirrors6.tuna.tsinghua.edu.cn/pypi/web
; download-mirror-no-fallback = False

[plugins]
enabled =
    blocklist_project

[blocklist]
packages =
    tf-nightly-gpu
    tf-nightly
    tensorflow-io-nightly
    tf-nightly-cpu
    tf-nightly-tpu
    pyagrum-nightly
    uselesscapitalquiz
    tf-nightly-intel
    tf-nightly-cpu-aws
    tf-nightly-macos
    tf-hub-nightly
    tf-estimator-nightly
    tf-models-nightly
    expose-localhost
    cyaxares
    genuine-fake
    pycg
    mpf
    proteus-cli
