# Only API definitions watched by the controller; no external workloads.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.6.0
