services:
  debian-ftpsync:
    build: dockerfiles/debian-ftpsync
    image: debian-ftpsync:latest
  condasync:
    build: conda-sync
    image: condasync:latest

  bandersnatch:
    build: bandersnatch
    image: pypa/bandersnatch:6.5.0-mod


# build only